### ISSUE TITLE
Potential Bug in Channel Area WebRAVE

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#293]
**Describe the bug**
WebRave is not opening Channel Area projects centered on the HUC. They are often mostly in view, but off in a corner somewhere. Additionally, there is a "tile timeout" that I am encountering in [10190002](https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/317bd443-38e6-47f7-9a3e-beef69b0c2f6). See video:
[![Alt-text](https://img.youtube.com/vi/XNAqlgDmO-4/0.jpg)](https://www.youtu.be/watch?v=XNAqlgDmO-4)

**To Reproduce**
Open a Channel Area project from the staging server

**Expected behavior**
Opening WebRave and seeing the HUC centered

**Screenshots**
How it opens now:
![image](https://user-images.githubusercontent.com/73319684/137549974-8271921a-56c1-4feb-b282-7284026f4fcf.png)

How I want it to open:
![image](https://user-images.githubusercontent.com/73319684/137550102-e9a8d2f4-7830-4dd5-8231-5ee658005f3a.png)

**Desktop (please complete the following information):**
 - OS: PC/Windows
 - Browser: Chrome
 - Version: WebRAVE staging server

**Riverscape Project (please complete the following information if relevent):**
 - Type: Channel Area
 - Warehouse Link: https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/d99292bd-613f-4253-abb5-5f23a1a72dcc (this is the one I put in the screenshots)
 - Layers Impacted N/A

**Comment by MattReimer** [comment]
Great issue, let me address this a point at a time:

1. The "timeout" issues are a problem tiling the rasters on the server. Nothing you need to worry about and nothing you can do about it. About 3% of the tiles are timing out. I can't solve these right now so maybe choose another project.
2. The map centering issue is a real thing and It's definitely something I need to fix. It's actually related to the following bugs that I know about:
    - https://github.com/Riverscapes/rs-web-monorepo/issues/156
    - https://github.com/Riverscapes/rs-web-monorepo/issues/146  

I think I'll close this issue for now since I'm already tracking the other bug but this is EXACTLY the kind of stuff I need to be reported.
