### ISSUE TITLE
TauDEM: Channel Line Input - Still Needed?

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#344]
I was making some updates to ArcRAVE TauDEM symbology and noticed that there is an input (Channel Line Input) [in the XML](https://github.com/Riverscapes/RiverscapesXML/blob/3348e39a184c45baa12af0af552ae1feae614915/RaveBusinessLogic/TauDEM.xml#L45) that doesn't show up in the project. I'm wondering if we need this and I should symbolize it or if I can remove it?

**Comment by MattReimer** [comment]
Hmmm. I don't see that line in any of the `project.rs.xml` files but if you look at the code it's still referenced there although it's inside a conditional that I'm not sure will ever fire.

https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/taudem/taudem/taudem.py#L120

Maybe @KellyMWhitehead can shed some light on this?

I'd say leave it there but since you have nothing to test there's probably nothing more we can do for now.

**Comment by joewheaton** [comment]
@MattReimer and @shelbysawyer this may have gone away (sort of) because we are now driving TauDEM projects (typically) off of Channel Area projects instead of a line. However, a TauDEM project can be either and many of our custom runs are. @philipbaileynar and @KellyMWhitehead any thoughts on this one? 

Good catch @shelbysawyer

**Comment by joewheaton** [comment]
Yes we do need to still allow lines as inputs. We have a bunch of examples in Anabranch on custom TauDEM runs you can use to test with @shelbysawyer. This will be basically extra-lines of BL that only appear if dataset is present.

**Comment by shelbysawyer** [comment]
@joewheaton Okay, sounds good. Thanks. Is there a way for me to identify those custom TauDEM runs in the warehouse to check them out?

**Comment by joewheaton** [comment]
> @joewheaton Okay, sounds good. Thanks. Is there a way for me to identify those custom TauDEM runs in the warehouse to check them out?

@MattReimer and @philipbaileynar  good for you to see this simple request. Not really. Look for some of the stuff from Klikitat, Kern and Dollar Ridge.

**Comment by MattReimer** [comment]
We could easily accomplish this with a tag convention. We already tag everything that's automatic with `Cybercastor` but right now I don't have a negative search of `NOT Cybercastor` so we could use `custom` for manual runs? 

I think this can be part of the conversation when we address the warehouse in the coming months. The search form that exists is rudimentary but the engine underneath it is hugely powerful and we could definitely be doing more.

**Comment by joewheaton** [comment]
> We could easily accomplish this with a tag convention. We already tag everything that's automatic with `Cybercastor` but right now I don't have a negative search of `NOT Cybercastor` so we could use `custom` for manual runs?
> 
For now this is fine. I don't think `NOT Cybercastor` is accurate but `custom_input` would be.  We also need to keep using our project specific tags (e.g. ELR_2020-23..... ). 

> I think this can be part of the conversation when we address the warehouse in the coming months. The search form that exists is rudimentary but the engine underneath it is hugely powerful and we could definitely be doing more.

Agreed. sounds good.

**Comment by MattReimer** [comment]
I think this ticket is complete. re-open if you disagree
