### ISSUE TITLE
WebRAVE and QRAVE roads layer have different legends and labels

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#359]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Roads
Type - Vector

## Issue
WebRAVE Roads layer has 2 labels for US and State recognized, qrave doesn't have labels. Legend for webrave collapses 3 road types into 1
WebRAVE
![image](https://user-images.githubusercontent.com/89225401/139951936-9fa77938-c567-41d8-9a00-fac87abfd148.png)
qRave
![image](https://user-images.githubusercontent.com/89225401/139952716-2c91a0f3-a94e-459d-af26-0c3397c150df.png)

**Comment by Cashe93** [comment]
@leallysmith, this layer is a bit tricky. Each road type (except for other) is symbolized with the same color and is differentiated by the line width. The issue is that we aren't able to show differences between line widths within the legend. That's why there are only two represented in the WebRAVE legend (notice how I tried to include most of the road types for black lines). Eventually, we will either need to figure out how to add line widths in the simple legend, or we may have to re-do these types of symbologies to be distinguished by color...but not yet.  Until further discussed, this is good for now. I did however get rid of labels for the sake of consistency.
