### ISSUE TITLE
Flow Direction in pyBRAT not displaying

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#364]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*:  Flow Direction
Type - Vector

## Issue
Not displaying in QRAVE or ArcRAVE and doesn't have arrows in WebRAVE, the attribute table doesn't have anything for flow direction so there is no lines or arrows in arc and q, in web flow direction is just displayed as lines

**Comment by Cashe93** [comment]
@wally-mac, the source of this issue was pointed out in #322. @MattReimer pointed out that there should be an attribute field that indicates the direction of flow. In sqlBRAT projects, this field exists, however, for pyBRAT projects this field does not exist. The symbology that was applied to legacy pyBRAT projects was just a single symbol applied to the entire network with no indication of the direction of flow. It looks fairly accurate, but I'm not sure how? I see two options (both of which are pretty easy). 1) if we trust that the single symbol applied to the entire network is accurate, we just have two symbologies; one for pyBRAT and one for sqlBRAT. 2) if the single symbol is misleading, we omit flow direction from the legacy pyBRAT tree. Either way, please advise. 


![image](https://user-images.githubusercontent.com/49880208/141834328-301e3125-c17e-44bc-a86b-80695493fe8b.png)

**Comment by joewheaton** [comment]
> @wally-mac, the source of this issue was pointed out in #322. @MattReimer pointed out that there should be an attribute field that indicates the direction of flow. 

@MattReimer that is not actually needed per se if you use the geometry start and stop points to infer it (what we did in pyBRAT).

**Comment by MattReimer** [comment]
Yeah, I'm not sure there's any explicit way to identify geometry start and stop in mapbox. It MAY be doing it by default which may explain:

>  It looks fairly accurate, but I'm not sure how?

But the UTF-8 fix with different arrows is a hack so we're pretty limited if it ends up not being right. 

To sum up:

- If there's a direction field it's easy
- If there isn't you're stuck with whatever is happening now (but I'm not hearing that it's wrong yet so maybe it's not an issue?)

**Comment by Cashe93** [comment]
All changes to this symbology have been made. There are now two symbologies (one for pyBRAT and one for sqlBRAT). WebRAVE symbology may still be misleading, but I've officially run out of ideas on how to improve it further. Closing this issue for now.
