### ISSUE TITLE
Filter Features in BRAT symbology

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#373]
@joewheaton implemented definition queries on 7 layers in [BRAT business logic ](https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/BRAT.xml#L13-L26) that are working really well in desktop RAVE.

WebRAVE cannot use definition queries and so the symbology needs to be enhanced for these 7 layers to filter out the features in question. 

@Cashe93 please enhance the BRAT symbology for WebRAVE to reflect the feature same feature filtering.

# Capacity

## Existing Dam Capacity

`"ReachCode"=46006 OR "ReachCode" = 33600 OR "ReachCode" = 55800`

## Existing Dam Size

`"ReachCode"=46006 OR "ReachCode" = 33600 OR "ReachCode" = 55800`

## Historic Dam Capacity

`"ReachCode"=46006 OR "ReachCode" = 55800`

## Historic Dam Size

`"ReachCode"=46006 OR "ReachCode" = 55800`

# Management

## Unsuitable or Limited Opportunities

`"ReachCode"=46006 OR "ReachCode" = 33600 OR "ReachCode" = 55800`

## Risk of Undesirable Dams

`ReachCode"=46006 OR "ReachCode" = 33600 OR "ReachCode" = 55800 `

## Restoration or Conservation Opportunities

`ReachCode"=46006 OR "ReachCode" = 55800`

**Comment by joewheaton** [comment]
@wally-mac and @Cashe93 this is fundamental for next Wednesday so that we do not show the entire network. To be clear it is the difference between:
![image](https://user-images.githubusercontent.com/9723905/140593968-5221eeaf-ea9c-4856-be62-0b17ddf4ae9a.png)
and what we want (shown below in Q):
![image](https://user-images.githubusercontent.com/9723905/140594066-2461f0d2-1c78-443e-985c-f44d3b15cd37.png)

To be clear, @philipbaileynar tells me this is to be done by making the vector symbology in MapBox to simply display nothing for the "other" "ReachCode"s and only displaying like you normally do the ones we want.  Please make sure you understand what exactly @MattReimer needs from you for this to work and where he wants you to put it in the RiverscapesXML repo (and what naming convention). I do not understand if this requires a change to business logic or not.

**Comment by wally-mac** [comment]
@joewheaton This is so slick and useful.

**Comment by wally-mac** [comment]
@Cashe93 if we are available today (Saturday) let's chat about this task.

**Comment by joewheaton** [comment]
See https://github.com/Riverscapes/RiverscapesXML/pull/375#issuecomment-964343723 for reference.

**Comment by joewheaton** [comment]
This is done. Though @MattReimer and I agreed that the functional fix in WebRAVE may not be our long-term fix.
