### ISSUE TITLE
Explore why Land Use Input in the pyBRAT is not displaying

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#393]
@joewheaton, the Land Use raster correctly displays in ArcRAVE but not in QRAVE or WebRAVE. [Here is a short video](https://youtu.be/9LsXfdN9InI) explaining why. This appears to be the same issue we had with vegetation rasters, pointed out in #164. The issue for categorical vegetation was solved by @MattReimer and tracked in #265. If time and budget allow, perhaps we can recruit @MattReimer to apply the same fix.

**Comment by joewheaton** [comment]
@Cashe93 thanks for chasing these down. One super minor thing... when we create issues like this from task lists in parent issue, don't forget to: Assign Ticket, add appropriate labels, assign to project(s), and if appropriate set a milestone.  Otherwise, these sub tickets can easily get lost. I appreciate all your efforts on this stuff.

**Comment by Cashe93** [comment]
This has been looked into with fixes in the works.
