### ISSUE TITLE
Housekeeping Question Related to Pull Requests - When and where do we delete branches

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#80]
@lauren-herbine and @shelbysawyer and I were confused on when we we should delete branches...
![image](https://user-images.githubusercontent.com/9723905/119063585-b6521e00-b996-11eb-8105-65157395c2b2.png)

Is it after the pull request is accepted we delete them both locally and remotely?

**Comment by philipbaileynar** [comment]
Our preferred workflow is:

1. The person who handles the pull request (typically @MattReimer) deletes the remote branch.
2. Once you see that the pull request is complete and the remove branch has been deleted, then you are responsible for deleting your local copy of the branch. Waiting until the remote branch is deleted by @MattReimer  is best because it ensures no work is lost if something goes wrong.

**Comment by MattReimer** [comment]
Hey @lauren-herbine and @shelbysawyer, @philipbaileynar is right on the money here.  When I merge a pull request there's a button for me to delete the branch which I always click. 

The best thing to do is to just look to make sure your commit messages are stacked on top of `master`. If you see them on `master` you've got good confidence that deleting your local is safe.

I know this is a lot of work for a couple of files. Having an issue AND a pull request AND a separate branch to commit one qml file is definitely a lot of work but it saves you needing to merge and rebase with each other so that's the tradeoff.

Rules I live by to make this easier:

* Always check where you are in git before you start work.
* Always push your work at the end of the day for safety.
* Makes sure to use the [closing syntax of github](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/linking-a-pull-request-to-an-issue) and then your issues get closed automatically when the pull request is merged

When we get comfortable with this we can look at combining issues that need to be pushed around the same time into "features" so they can all be dealt with using a single pull request. 

I think things are going really well though and I'm happy to do a little tutorial sometime if we want to upgrade our git game even more.

**Comment by shelbysawyer** [comment]
Thanks @philipbaileynar and @MattReimer for this info. Getting in some repetition over here and each one is a little smoother than the last. I'd love a tutorial to up my Git game. Thanks!

**Comment by MattReimer** [comment]
Closing this issue since there's no action necessary for now.
